server:
  port: 80

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: product_route
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**
