server:
  port: 11000


spring:
  profiles:
    include: sharding
  redis:
    host: 192.168.60.130
    password: Wyj123!@!
    lettuce:
      pool:
        max-wait: -1
        max-active: 8
        max-idle: 0
