server:
  port: 9000

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

app:
  threadpool:
    corePoolSize: 24
    maximumPoolSize: 48
    keepAliveTime: 1
#    timeUnit: java.util.concurrent.TimeUnit.MINUTES
    queueSize: 1000