server:
  port: 10000


spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  elasticsearch:
    rest:
      uris:
        - http://192.168.60.130:9200

logging:
  level:
    org.springframework.data.elasticsearch: trace
    tracer: trace